name: CI
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: スクレイピング
        run: |
          git clone https://github.com/yuzuru-program/scraping-ruby-yahoo.git ci
          cd ci
          sudo gem install nokogiri
          ruby index.rb
